services:
  gerald-db:
    image: postgres:16-alpine
    container_name: gerald-db
    hostname: gerald-db
    restart: unless-stopped
    ports:
      - 5430:5430
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BaristaDB
    volumes:
      - ./gerald-db-data:/var/lib/postgresql/data
    networks:
      - quickstack-platform-interconnect
    command: -p 5430
  gerald-runner:
    container_name: gerald_runner
    hostname: gerald_runner
    image: barista:latest
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - gerald-db
    networks:
      - quickstack-platform-interconnect

networks:
  quickstack-platform-interconnect:
    external: true